name: Testing 

on: [push]

jobs:
  selenium-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # ✅ Dynamically Install Google Chrome & Matching ChromeDriver
      - name: Install Google Chrome & ChromeDriver
        run: |
          sudo apt update
          
          # Install Google Chrome
          wget -q -O google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome.deb
          rm google-chrome.deb
          
          # Get installed Chrome version
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d. -f1)
          
          # Fetch the matching ChromeDriver version
          CHROMEDRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          
          # Download and install the correct Chromedriver
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          rm chromedriver_linux64.zip
          
          # Verify installed versions
          google-chrome --version && chromedriver --version

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Selenium Tests
        run: python main.py

      - name: Show All Test Logs in Console
        run: cat test_*.log || true  # Allows the command to fail without affecting the workflow

      - name: Upload Test Logs
        uses: actions/upload-artifact@v4
        with:
          name: selenium-logs
          path: test_*.log
